<?php

/*
|--------------------------------------------------------------------------
| Sayfa İçerikleri
|--------------------------------------------------------------------------
| Tüm metin/veri içeriği. Kaynak: https://hukumdar.com.tr/ (Hükümdar Bilişim).
*/

return [

    /* ---------------------------------------------------------------- Hero */
    'hero' => [
        'badge' => 'Geleceği Şekillendiren Dijital Hizmetler',
        'rating' => '4.9',
        'rating_count' => '300+',
        'highlights' => ['2008’den bu yana 16+ yıllık deneyim', '300’den fazla kurumsal marka referansı', '7/24 satış öncesi ve teknik destek'],
        'slides' => [
            [
                'kicker'      => 'Hükümdar Web Tasarım Ajansı',
                'title'       => 'Hükümdar <span class="text-gradient-light">Web Tasarım Ajansı</span>',
                'description' => '2008 yılından bu yana 300+ kurumsal markaya özel tasarım, güçlü SEO ve yüksek hız odaklı kurumsal web çözümleri sunuyoruz.',
                'image'       => 'images/slider/slide-hukumdar-1.png',
                'cta_primary'   => ['label' => 'Web Tasarım Hizmetimiz', 'href' => '/hizmetler/web-tasarim'],
                'cta_secondary' => ['label' => 'Referanslarımız', 'href' => '/referanslar'],
            ],
            [
                'kicker'      => 'E-Ticaret Çözümleri',
                'title'       => 'E-Ticaret <span class="text-gradient-light">Çözümleri</span>',
                'description' => 'Pazaryeri ve 21 banka sanal POS entegrasyonlarıyla güçlendirilmiş e-ticaret altyapısıyla satışlarınızı katlayın.',
                'image'       => 'images/slider/slide-hukumdar-2.png',
                'cta_primary'   => ['label' => 'E-Ticaret Paketleri', 'href' => '/fiyatlar'],
                'cta_secondary' => ['label' => 'Detaylı Bilgi', 'href' => '/hizmetler/e-ticaret'],
            ],
            [
                'kicker'      => 'Dijital Pazarlama & SEO',
                'title'       => 'Dijital Pazarlama & <span class="text-gradient-light">SEO Hizmetleri</span>',
                'description' => 'Google'da üst sıralara çıkın. SEO, Google Ads ve sosyal medya yönetimiyle markanızı dijitalde zirveye taşıyoruz.',
                'image'       => 'images/slider/slide-hukumdar-3.png',
                'cta_primary'   => ['label' => 'SEO Hizmetimiz', 'href' => '/hizmetler/seo'],
                'cta_secondary' => ['label' => 'Teklif Alın', 'href' => '/iletisim'],
            ],
            [
                'kicker'      => 'Mobil & Özel Yazılım',
                'title'       => 'Özel Yazılım & <span class="text-gradient-light">Mobil Uygulama</span>',
                'description' => 'İş süreçlerinize özel otomasyon, CRM ve iOS / Android mobil uygulama çözümleriyle markanızı geleceğe taşıyın.',
                'image'       => 'images/slider/slide-hukumdar-4.png',
                'cta_primary'   => ['label' => 'Mobil Uygulama', 'href' => '/hizmetler/mobil-uygulama'],
                'cta_secondary' => ['label' => 'İletişime Geçin', 'href' => '/iletisim'],
            ],
        ],
    ],

    /* ----------------------------------------------- Güvenen markalar */
    'brands' => [
        ['name' => 'Koçak Gold', 'logo' => 'images/brands/kocak-gold.jpg'],
        ['name' => 'Tuğra Halı', 'logo' => 'images/brands/tugra-hali.jpg'],
        ['name' => 'BanaKitapAl', 'logo' => 'images/brands/banakitapal.jpg'],
        ['name' => 'Hobi İstasyonu', 'logo' => 'images/brands/hobi-istasyonu.jpeg'],
        ['name' => 'Loop Bisiklet', 'logo' => 'images/brands/loop-bisiklet.png'],
        ['name' => 'Kron Bisiklet', 'logo' => 'images/brands/kron-bisiklet.png'],
        ['name' => 'Lacivert Mimarlık', 'logo' => 'images/brands/lacivert-mimarlik.jpeg'],
        ['name' => 'AIRLED', 'logo' => 'images/brands/airled.jpg'],
        ['name' => 'Villan Burada', 'logo' => 'images/brands/villan-burada.png'],
    ],

    /* ---------------------------------------------------------- Hizmetler */
    'services' => [
        'eyebrow' => 'Hizmetlerimiz',
        'title' => 'Geleceği şekillendiren dijital ve yazılım çözümleri',
        'description' => 'Teknolojiyi yaratıcı fikirlerle birleştirerek, yenilikçi ve etkili dijital stratejiler tasarlıyoruz. Hedefimiz, müşterilerimize rekabet avantajı kazandırarak sürdürülebilir büyüme sağlamaktır.',
        'items' => [
            [
                'slug' => 'web-tasarim',
                'icon' => 'layout',
                'seo_title' => 'Web Tasarım - Hükümdar Bilişim',
                'title' => 'Web Tasarım',
                'short' => 'Hazır değil, özel tasarım modüllerle kullanıcı dostu kurumsal web siteleri.',
                'desc' => '16 yıllık tecrübesiyle Hükümdar Bilişim; bilgisayar mühendisleri ve yaratıcı ekibiyle sadece estetik değil, işlevsel ve kullanıcı dostu özel web tasarımları sunar.',
                'features' => ['Özel tasarım modüller', 'Yönetim paneli & QR Kod', '21 banka POS & SEO uyumlu'],
                'intro' => 'Hükümdar Bilişim, 16 yıllık tecrübesiyle dijital dünyada fark yaratmak isteyen markaların en güçlü çözüm ortağıdır. Kurumsal büyük markalarla çalışarak edindiğimiz deneyim ve uzmanlık, her projede mükemmel sonuçlar elde etmemizi sağlıyor. Bünyemizdeki bilgisayar mühendisleri ve yaratıcı ekibimizle, hazır kalıpların ötesine geçerek kullanıcı deneyimini (UX) ve estetiği birleştiren projeler geliştiriyoruz.',
                'deliverables' => [
                    ['title' => 'WhatsApp & Teklif Modülü', 'desc' => 'Ziyaretçileriniz doğrudan WhatsApp üzerinden ulaşabilir veya teklif sayfanızdan hızlıca teklif alabilir.'],
                    ['title' => 'Gelişmiş Yönetim Paneli', 'desc' => 'Web Site Yönetim Paneli sayesinde tüm sitenizi, ürün ve hizmetlerinizi istediğiniz an kolaylıkla yönetebilirsiniz.'],
                    ['title' => 'Güçlü SEO & Google Uyumlu Yapı', 'desc' => 'Tam Google ve arama motorları uyumlu altyapı ile paylaştığınız sayfalar üst sıralarda yer alır.'],
                    ['title' => 'QR Kod & Katalog Modülü', 'desc' => 'QR kod oluşturarak müşterilerinize katalog ve PDF sunumlarınızın linklerini anında gösterebilirsiniz.'],
                    ['title' => 'Satış & Sanal POS Modülü', 'desc' => '21 banka ile uyumlu sanal POS yönetim paneli üzerinden güvenle online ödeme alabilirsiniz.'],
                    ['title' => 'Responsive & Hızlı Açılabilir Tasarım', 'desc' => 'Özgün içerikli, tüm cihazlara tam uyumlu (responsive) ve yüksek hızda açılan modern arayüz.'],
                ],
            ],
            [
                'slug' => 'e-ticaret',
                'icon' => 'cart',
                'seo_title' => 'E-Ticaret Paketleri & Özel E-Ticaret Yazılımı',
                'title' => 'E-Ticaret Paketleri',
                'hero_bg' => '/images/e-ticaret-hero.png',
                'short' => 'Kendi kendine yetebilen, pazaryeri ve 21 banka POS entegreli e-ticaret sistemleri.',
                'desc' => 'Fiziksel mağazanızın sınırlarına takılmayın. Markanızı 7/24 açık, dünyanın her yerinden ulaşılabilir global bir vitrine dönüştürün.',
                'features' => ['Pazaryeri & XML entegrasyonu', '21 Banka Sanal POS', 'iOS & Android Mobil Uygulama'],
                'intro' => '2009 yılından bugüne kadar e-ihracat, e-ticaret, mühendislik ve yazılım alanında uzman danışmanlarımızla kendi kendine yetebilen e-ticaret siteleri oluşturuyoruz. Güçlü, güvenli ödeme altyapısına sahip e-ticaret yazılımımız stok ve sipariş akışını otomatikleştirir, operasyon maliyetlerini düşürür ve dönüşüm oranlarını yukarı taşır.',
                'deliverables' => [
                    ['title' => 'Stok & Sınırsız Ürün Yönetimi', 'desc' => 'Varyantlı veya tek olarak sınırsız ürün ekleyin, Excel ve XML ile toplu ürün yükleyin ve bayilerinize XML çıktısı verin.'],
                    ['title' => 'Pazaryeri Entegrasyonları', 'desc' => 'Hepsiburada, N11, Amazon.com.tr, ePttAVM ve InstaShop siparişlerinizi tek panelden yönetin.'],
                    ['title' => '21 Banka Anlaşmalı Sanal POS', 'desc' => '3D Secure destekli 21 banka sanal POS, havale/EFT bildirimleri ve kapıda ödeme seçenekleriyle kolay ödeme alın.'],
                    ['title' => 'Sipariş & Kargo Otomasyonu', 'desc' => 'Sipariş durum, kargo takibi, iptal/iade ve arıza bildirimlerini tek ekrandan yönetin.'],
                    ['title' => 'Pazarlama & WhatsApp Sipariş', 'desc' => 'Vitrin yönetimi, kampanya modülleri, müşteri soru-cevap sistemi ve WhatsApp üzerinden sipariş alma.'],
                    ['title' => 'SEO & Sosyal Medya Uyumlu', 'desc' => 'Arama motorlarına ve sosyal medya mağazalarına tam uyumlu, hızlı ve ölçeklenebilir mimari.'],
                ],
            ],
            [
                'slug' => 'mobil-uygulama',
                'icon' => 'sparkles',
                'seo_title' => 'Mobil Uygulama Geliştirme',
                'title' => 'Mobil Uygulama',
                'short' => 'iOS ve Android platformları için React tabanlı, bildirim ve ödeme destekli mobil uygulamalar.',
                'desc' => 'Mobil uygulama ile kullanıcılara doğrudan dokunun. Push bildirim, QR/Barkod, ödeme sistemleri ve kolay yönetim panelli iOS & Android uygulamalar geliştiriyoruz.',
                'features' => ['Push Notification sistemi', 'React yazılım mimarisi', 'Lokasyon & ödeme modülleri'],
                'intro' => 'Mobil uygulama ajansı olarak her geçen gün yeni teknoloji ile kendini geliştiren Hükümdar Bilişim; 2008-2009 yıllarından bu yana işletmelerin arka plan sistemlerini ve ön yüzlerini mobil dünyaya taşıyor. Rakiplerinizin önüne geçmeniz için iOS ve Android cihazlarda 7/24 çalışan, estetik ve yüksek performanslı mobil uygulamalar tasarlıyoruz.',
                'deliverables' => [
                    ['title' => 'Push Notification Bildirim Sistemi', 'desc' => 'Mobil uygulama kullanıcılarınıza anlık ve ücretsiz kampanya/bilgilendirme bildirimleri gönderin.'],
                    ['title' => 'React Yazılım Kodlaması', 'desc' => 'Modern React mimarisi ile hem iOS hem Android cihazlarda yüksek hız ve akıcı kullanıcı deneyimi.'],
                    ['title' => 'Ödeme & 21 Banka POS', 'desc' => 'Mobil uygulama içerisine dilediğiniz ödeme yöntemlerini ve 21 banka anlaşmalı sanal POS altyapısını ekleyin.'],
                    ['title' => 'QR Kod & Barkod Okuyucu', 'desc' => 'Ürün sayım, stok kontrol ve çalışma alanı paylaşım işlemlerini cihaz kamerasıyla anında gerçekleştirin.'],
                    ['title' => 'Asistan & Canlı Destek Modülü', 'desc' => 'Uygulama içi video/fotoğraf gönderimi, çağrı, not, hatırlatma ve teknik destek özellikleri.'],
                    ['title' => 'Lokasyon Bazlı Özellikler', 'desc' => 'Projenize özel harita, konum takibi ve lokasyon öncelikli akıllı modüller.'],
                ],
            ],
            [
                'slug' => 'ozel-yazilim',
                'icon' => 'code',
                'seo_title' => 'Özel Yazılım Geliştirme',
                'title' => 'Özel Yazılım',
                'short' => 'Bilgisayar mühendisi ekibimizle iş süreçlerinizi otomatikleştiren özel yazılımlar.',
                'desc' => 'Bir fikriniz var ve bunu hayata geçirecek mühendis ekibi mi arıyorsunuz? Üretim, muhasebe, CRM ve otomasyon yazılımlarını sıfırdan geliştiriyoruz.',
                'features' => ['Bilgisayar mühendisi kadrosu', 'ERP / Muhasebe entegrasyonu', 'Güçlü veritabanı & otomasyon'],
                'intro' => 'Özel yazılım ile fikirlerinizi projelendiriyoruz. Bilgisayar mühendisi ekibimizle iş süreçlerinizi en ince ayrıntısına kadar analiz ediyor, üretimden muhasebeye kadar tüm operasyonunuzu otomasyon haline getiren güvenli ve ölçeklenebilir yazılımlar üretiyoruz.',
                'deliverables' => [
                    ['title' => 'Detaylı Analiz & Planlama', 'desc' => 'Fikirleriniz modüllere dökülmeden önce mühendis ekibimizle uçtan uca mimari planlama yapılır.'],
                    ['title' => 'Özel Modül Geliştirme', 'desc' => 'İhtiyacınız olan tüm iş akışlarını yazılım içerisinde size özel birer özelliğe dönüştürüyoruz.'],
                    ['title' => 'Üretim & Muhasebe Entegrasyonu', 'desc' => 'Mevcut üretim, stok veya muhasebe sistemlerinizle tam entegre çalışan modüller.'],
                    ['title' => 'İş Akışı Otomasyonu', 'desc' => 'Manuel süreçleri ortadan kaldırarak üretiminizi ve operasyonunuzu tam otomasyon haline getiriyoruz.'],
                    ['title' => 'Güçlü Veritabanı Mimarisi', 'desc' => 'Yüksek işlem kapasitesine sahip, güvenli ve hızlı veritabanı teknolojileri.'],
                    ['title' => 'Tam Bağımsız Yönetim', 'desc' => 'Kendi başınıza yönetebileceğiniz, başka hiçbir yere bağımlı kalmayacağınız esnek panel yapısı.'],
                ],
            ],
            [
                'slug' => 'seo',
                'icon' => 'search',
                'seo_title' => 'SEO Hizmeti — Google’da Üst Sıralara Çıkın',
                'title' => 'SEO Hizmeti',
                'short' => 'Site içi SEO, backlink mimarisi ve özgün içeriklerle Google’da kalıcı liderlik.',
                'desc' => 'Sadece güzel bir web sitesine sahip olmak yeterli değildir; potansiyel müşterilerin sizi bulabilmesi için güçlü bir SEO stratejisi kurguluyoruz.',
                'features' => ['Site içi & teknik SEO', 'Doğal backlink mimarisi', 'Anahtar kelime & rakip analizi'],
                'intro' => 'Markanızın web sitesindeki içerik, görsel, URL yapısı ve başlıkların SEO kurallarına tam uyumlu olması gerekir. Alanında uzman kadromuzla markanızın hizmet alanlarını ve hikayesini baz alarak; anahtar kelime analizinden backlink inşasına kadar tüm süreçleri yönetiyor ve sizi Google aramalarında üst sıralara taşıyoruz.',
                'deliverables' => [
                    ['title' => 'Anahtar Kelime & Rakip Analizi', 'desc' => 'Sektörünüzde rakiplerinizin kullandığı etiketleri ve sizi üst sıralara taşıyacak kelimeleri analiz ediyoruz.'],
                    ['title' => 'Site İçi (On-Page) SEO', 'desc' => 'H1-H6 başlık oranları, Title/Description alanları, kısa URL yapısı ve görsel boyutlandırma optimizasyonu.'],
                    ['title' => 'Backlink Mimarisi & Dış SEO', 'desc' => 'Alan adı otoritenizi güçlendiren doğru biçimlendirilmiş backlink ve yerel haber/blog tanıtım çalışmaları.'],
                    ['title' => 'Düzenli SEO Uyumlu Blog', 'desc' => 'Hedef kitlenizin dikkatini çeken ve organik trafiği büyüten düzenli makale üretimi.'],
                    ['title' => 'Teknik SEO & SSL Kontrolü', 'desc' => 'Site hızı, mobil uyumluluk, dinamik site haritaları, kırık link kontrolü ve güncel SSL yapılandırması.'],
                    ['title' => 'Şeffaf Performans Takibi', 'desc' => 'Sıralama yükselişlerini ve organik trafik artışını gösteren düzenli analiz raporları.'],
                ],
            ],
            [
                'slug' => 'sosyal-medya',
                'icon' => 'share',
                'seo_title' => 'Sosyal Medya Yönetimi',
                'title' => 'Sosyal Medya Yönetimi',
                'short' => 'Veri odaklı strateji, Reels prodüksiyonu ve aylık içerik takvimiyle sosyal medyada hükmedin.',
                'desc' => 'Instagram, Facebook, LinkedIn ve X platformlarında markanızın ses tonunu oluşturuyor, özgün içerik ve reklamlarla sadık müşteriler kazandırıyoruz.',
                'features' => ['Reels & video prodüksiyonu', 'Aylık içerik takvimi', 'Meta Business reklam yönetimi'],
                'intro' => 'Sosyal medya, günümüzde markaların müşterileriyle buluştuğu en güçlü vitrindir. Ancak etkili bir yönetim sadece post paylaşmaktan çok daha fazlasını gerektirir. Algoritmaların dilinden anlayan ekibimizle markanızın hikayesini doğru stratejiyle anlatıyor, etkileşiminizi ve satışlarınızı büyütüyoruz.',
                'deliverables' => [
                    ['title' => 'Stratejik Yol Haritası', 'desc' => 'Mevcut durumunuzu analiz ediyor; satış, bilinirlik ve trafik hedeflerinize en uygun dijital stratejiyi kurguluyoruz.'],
                    ['title' => 'Hesap Kurulumu & Bio SEO', 'desc' => 'Profil resminden biyografiye, öne çıkan hikayelerden iletişim butonlarına kadar sayfanızı optimize ediyoruz.'],
                    ['title' => 'Reels & Video Prodüksiyonu', 'desc' => 'Algoritmaların en sevdiği Reels ve kısa videolarla markanızın keşfette yer almasını sağlıyoruz.'],
                    ['title' => 'Aylık İçerik Takvimi', 'desc' => 'Tüm paylaşımları bir ay önceden planlayarak düzenli ve istikrarlı bir yayın akışı kuruyoruz.'],
                    ['title' => 'Meta Business Reklam Yönetimi', 'desc' => 'Facebook & Instagram reklam bütçenizi en düşük maliyetle en yüksek dönüşümü (ROI) alacak şekilde yönetiyoruz.'],
                    ['title' => 'Topluluk & İtibar Yönetimi', 'desc' => 'Mesaj ve yorumları profesyonel dille yanıtlayarak marka sadakatini ve online itibarınızı koruyoruz.'],
                ],
            ],
            [
                'slug' => 'google-ads',
                'icon' => 'target',
                'seo_title' => 'Google Ads (AdWords) Reklam Yönetimi',
                'title' => 'Google Ads Reklamları',
                'short' => 'Satış niteliklerinize uygun anahtar kelime stratejisiyle Google’da anında üst sıralar.',
                'desc' => 'Web sitenizin kurulumu sonrasında kısa bir çalışmayla Google Ads reklamlarınızı entegre ediyor, doğru kelimelerle satışlarınızı hızla artırıyoruz.',
                'features' => ['Pazarlama odaklı kelimeler', 'Bütçe & dönüşüm optimizasyonu', 'Algoritma & politika takibi'],
                'intro' => 'Google Ads (AdWords), klasik kelime etiketlendirmesinden farklı ve uzmanlık gerektiren bir strateji ister. Profesyoneller tarafından yönetilmediğinde bütçe kayıplarına yol açabilir. Hükümdar Bilişim olarak ürün ve hizmetlerinizin niteliklerine göre pazarlama odaklı kelimeler üretiyor, kısa sürede potansiyel müşterilerinizde ve satışlarınızda gözle görülür artış sağlıyoruz.',
                'deliverables' => [
                    ['title' => 'Satış Odaklı Kelime Üretimi', 'desc' => 'Ürün ve hizmetlerinizin doğru kitleye ulaşması için dönüşüm oranı yüksek anahtar kelimeler belirliyoruz.'],
                    ['title' => 'Kampanya & Hesap Güvenliği', 'desc' => 'Google reklam politikalarına %100 uyumlu, askıya alınma risklerinden korunan güvenli kampanya kurulumu.'],
                    ['title' => 'E-Ticaret & Alışveriş Reklamları', 'desc' => 'Ürünlerinizin Google aramalarında doğrudan görsel ve fiyatıyla üst sıralarda çıkmasını sağlıyoruz.'],
                    ['title' => 'Maliyet & ROAS Optimizasyonu', 'desc' => 'Tıklama başına maliyetleri düşürürken reklam harcaması getirisini (ROAS) maksimize ediyoruz.'],
                    ['title' => 'Sürekli Güncelleme Takibi', 'desc' => 'Google’ın sunduğu yeni reklam formatlarını ve algoritma güncellemelerini projelerinize anında yansıtıyoruz.'],
                    ['title' => 'Detaylı Dönüşüm Raporlama', 'desc' => 'Hangi kelimenin ve reklamın ne kadar satış getirdiğini şeffaf raporlarla sunuyoruz.'],
                ],
            ],
            [
                'slug' => 'bilisim-danismanligi',
                'icon' => 'shield',
                'seo_title' => 'Projeleriniz İçin Bilişim Danışmanlığı',
                'title' => 'Bilişim Danışmanlığı',
                'short' => 'Yazılım güvenliği, IT desteği, CRM/ERP ve iş akış yönetimi için mühendis danışmanlığı.',
                'desc' => 'Projeniz için ekip kurmak, yazılımınızın güvenliğini sağlamak veya iş süreçlerinizi dijitalleştirmek istediğinizde mühendis kadromuzla yanınızdayız.',
                'features' => ['24 saatte çökme/kurtarma garantisi', 'CRM / ERP & IT desteği', 'İş akış yönetimi çözümleri'],
                'intro' => 'Bilişim danışmanlığı hizmetimizde; yaptırdığınız yazılımların güvenliğini, doğru çalışma yöntemlerini ve kurumsal yapınızı koruyarak entegre sistem çalışmanızı sağlıyoruz. Gerçekleştirdiğimiz her işlem ve sunduğumuz her hizmet bilgisayar mühendislerimiz tarafından takip edilmektedir.',
                'deliverables' => [
                    ['title' => '24 Saatte Kurtarma Garantisi', 'desc' => 'İnternet sitelerinizin herhangi bir çökme ya da bozulma durumunda 24 saat içerisinde eski haline getirme garantisi.'],
                    ['title' => 'CRM, ERP & Özel Yazılım Yönetimi', 'desc' => 'İş süreçlerinizi web üzerinden takip edebileceğiniz CRM ve ERP çözümlerinin en uygun prosedürlerle üretilmesi.'],
                    ['title' => 'IT Desteği & Sunucu Bakımı', 'desc' => 'Alan adı, hosting planlaması ve server/bilgisayar sistemlerinizin düzenli teknik bakımı.'],
                    ['title' => 'Ekip Kurulumu & Proje Yönetimi', 'desc' => 'Projeniz için doğru teknik ekibi kurma, yönetme ve size düzenli mühendislik raporu sunma.'],
                    ['title' => 'İçerik & Arama Motoru Yönetimi', 'desc' => 'Kurumsal içerik editörlüğü, Google Ads ve SEO süreçlerinin tek merkezden koordinasyonu.'],
                    ['title' => 'İş Akış Yönetimi Çözümleri', 'desc' => 'İş süreçlerini iyileştirmek isteyen şirketler için kolay kullanımlı dijital iş akış sistemleri.'],
                ],
            ],
            [
                'slug' => 'urunlerimiz',
                'icon' => 'bolt',
                'seo_title' => 'Hazır Yazılım Ürünlerimiz — QR Menü, Otel, Acenta, Haber, Kurye',
                'title' => 'Yazılım Ürünlerimiz',
                'short' => 'QR Menü, Otel Web Tasarımı, Acenta Yönetimi, Haber Scripti, Kurye Otomasyonu ve Teklif Yazılımı.',
                'desc' => 'Müşterilerinize mükemmel bir deneyim sunmak ve işletmenizi modernleştirmek için geliştirdiğimiz sektörel hazır yazılım ürünlerimizi keşfedin.',
                'features' => ['QR Menü & Restoran Sistemi', 'Otel, Acenta & Haber Yazılımı', 'Kurye Takip & Teklif Otomasyonu'],
                'intro' => 'Hükümdar Bilişim olarak farklı sektörlerin ihtiyaçlarına özel, anında kullanıma hazır ve sürekli güncellenen yazılım ürünleri geliştirdik. İşletmenizi modernleştiren 6 ana yazılım ürünümüzle operasyonunuzu hızlandırın.',
                'deliverables' => [
                    ['title' => 'QR Menü Yazılımı', 'desc' => 'Restoran ve kafeler için müşterilerinize mükemmel bir deneyim sunan, anlık fiyat ve ürün güncellemeli dijital QR Menü.'],
                    ['title' => 'Otel Web Tasarımı & Rezervasyon', 'desc' => 'Oteller için özel olarak hazırlanmış, oda ve rezervasyon yönetimi sunan profesyonel konaklama web sistemi.'],
                    ['title' => 'Acenta Yönetim Yazılımı', 'desc' => 'Acenta sahiplerinin kendi satışlarını yönetebilecekleri ve kazançlarını anlık takip edebilecekleri B2B/B2C sistem.'],
                    ['title' => 'Haber Yazılımı (Haber Scripti)', 'desc' => 'Google algoritmalarıyla anlık uyumlu, zengin modüllü ve sürekli güncellenen yüksek trafikli haber portalı yazılımı.'],
                    ['title' => 'Kurye Takip ve Otomasyon Yazılımı', 'desc' => 'Kuryelere otomatik paket ataması yapan, Yemeksepeti ve Getir entegrasyonlu hızlı kurye yönetim sistemi.'],
                    ['title' => 'Profesyonel Teklif Yazılımı', 'desc' => 'Müşterilerinize kolay ve kurumsal şekilde teklifler iletmenizi ve onay süreçlerini kontrol etmenizi sağlayan sistem.'],
                ],
            ],
        ],
    ],

    /* --------------------------------------------------------- Neden Biz */
    'why' => [
        'eyebrow' => 'Neden Bizi Seçmelisiniz?',
        'title' => '300’den fazla marka bize güveniyor ve bizimle çalışıyor',
        'description' => 'Teknolojiyi yaratıcı fikirlerle birleştirerek, yenilikçi ve etkili dijital stratejiler tasarlıyoruz.',
        'items' => [
            ['no' => '01', 'icon' => 'target', 'title' => 'Memnuniyet Önceliği', 'desc' => 'Öncelikle müşterilerimizin iş hedeflerini anlamaya çalışırız. Daha sonra tüm kararlar bu hedefler göz önünde bulundurularak alınır.'],
            ['no' => '02', 'icon' => 'users', 'title' => 'Harika İnsanlar & Uzman Kadro', 'desc' => 'Şirket içi yeteneklerimiz; yazılım mühendisleri, SEO uzmanları ve içerik yöneticileriyle ajans ve kurumsal deneyimlerin dengeli bir karışımını temsil ediyor.'],
            ['no' => '03', 'icon' => 'bolt', 'title' => 'Mükemmel Destek', 'desc' => 'Bizimle kolayca iletişim kurabilirsiniz. Teknik destek için ortalama bekleme süremiz olağanüstü hızlıdır.'],
            ['no' => '04', 'icon' => 'shield', 'title' => '2008’den Beri Köklü Güvence', 'desc' => 'Kamu kurumlarından holdinglere kadar 1200+ projede kanıtlanmış 16 yılı aşkın mühendislik ve tasarım tecrübesi.'],
        ],
    ],

    /* --------------------------------------------------------- Hakkımızda */
    'about' => [
        'eyebrow' => 'Hakkımızda — Kuruluş 2008',
        'title' => 'Web dünyasının modern ve profesyonel yüzü: Hükümdar Bilişim',
        'description' => 'Hükümdar Bilişim Hizmetleri, kurulduğu 2008 yılından bu yana yapmış olduğu web tasarımlarında ve özel yazılımlarda çağdaş teknolojiyi gururla temsil eden bir teknoloji ajansıdır. Bünyesinde bilgisayar mühendisleri, bilgi teknolojileri uzmanları, SEO uzmanları ve içerik yöneticilerini barındıran yüksek kapasiteli web yazılım ve hosting sağlayıcısıdır.',
        'points' => [
            '2008 yılından bu yana 16+ yıllık kesintisiz sektör deneyimi',
            'Tekfen Holding, Fıratpen, Atasay, Altınbaş, Koçak Gold ve Bakanlık referansları',
            'Bilgisayar mühendisleri ve ödüllü tasarım kadrosu',
            'Türkiye’nin tüm bölgelerine aynı şehirdeymiş gibi hızlı ve güvenilir destek',
        ],
        'mission' => 'Misyonumuz; günlük düşünen değil, hayallerini ve hedeflerini yıllara yayarak sunduğumuz bilişim, özel yazılım, e-ticaret ve SEO hizmetlerini sürekli hale getirmek; müşterilerimize rekabet avantajı kazandırarak dijital dünyada sürdürülebilir büyüme sağlamaktır.',
        'vision' => 'Vizyonumuz; değişimci ve yenilikçi bir anlayışla en ileri düzeyde teknik donanıma sahip mühendis ve tasarım kadromuzla Türkiye’nin ve dünyanın her noktasındaki işletmeleri geleceğin dijital ihtiyaçlarına hazır hale getirmektir. — Semih HÜKÜMDAR',
        'values' => [
            ['icon' => 'sparkles', 'title' => 'Yaratıcılık', 'desc' => 'Potansiyel müşterilerinizin dikkatini çeken ve sunduklarınıza ilgi duymalarını sağlayan özgün çalışmalar yapıyoruz.'],
            ['icon' => 'target', 'title' => 'Odaklanma', 'desc' => 'Müşterilerimizin hedeflerine ulaşmaları için odaklı ve kararlı bir yaklaşımla çalışıyor, işinize değer katacak çözümler geliştiriyoruz.'],
            ['icon' => 'bolt', 'title' => 'Optimizasyon', 'desc' => 'Hedeflerinizi hayata geçiriyoruz! Başarımızı, müşterilerimize sunduğumuz somut ve etkili sonuçlarla ölçüyoruz.'],
            ['icon' => 'shield', 'title' => 'Kalıcı Dostluk & Güven', 'desc' => 'Tüm işlerimizi zamanında ve talep edildiği şekilde teslim ederek müşterilerimizle yıllara yayılan kalıcı güven kuruyoruz.'],
        ],
    ],

    /* ---------------------------------------------------------- İstatistik */
    'stats' => [
        'eyebrow' => 'Rakamlarla Hükümdar Bilişim',
        'title' => '2008’den bugüne kanıtlanmış başarı',
        'description' => 'Holdinglerden kamu kurumlarına, KOBİ’lerden global e-ticaret markalarına kadar yüzlerce işletmenin dijital çözüm ortağıyız.',
        'items' => [
            ['value' => 300, 'suffix' => '+', 'label' => 'Güvenen Marka', 'icon' => 'users'],
            ['value' => 16, 'suffix' => '+', 'label' => 'Yıllık Tecrübe', 'icon' => 'calendar'],
            ['value' => 1200, 'suffix' => '+', 'label' => 'Tamamlanan Web & Yazılım', 'icon' => 'award'],
            ['value' => 24, 'suffix' => ' Saat', 'label' => 'Acil Kurtarma & Destek', 'icon' => 'shield'],
        ],
    ],

    /* ------------------------------------------------------------- Süreç */
    'process' => [
        'eyebrow' => 'Çalışma Metodolojimiz',
        'title' => 'Stratejiden somut sonuçlara 5 adım',
        'description' => 'Müşterileriniz, rakipleriniz ve arama motoru ortamınız hakkında derinlemesine araştırmalar yürüterek projenizi geleceğe hazırlıyoruz.',
        'steps' => [
            ['no' => '01', 'title' => 'Marka Stratejisi & Analiz', 'desc' => 'Müşterileriniz, rakipleriniz ve arama motoru ortamınız hakkında derinlemesine araştırmalar yürütmeye odaklanırız.'],
            ['no' => '02', 'title' => 'Yaratıcılık & Özel Tasarım', 'desc' => 'Potansiyel müşterilerinizin dikkatini çeken ve sunduklarınıza ilgi duymalarını sağlayan modern UI/UX tasarımlar hazırlıyoruz.'],
            ['no' => '03', 'title' => 'Odaklanma & Web Geliştirme', 'desc' => 'İyi organize edilmiş bir mühendislik stratejisiyle web sitenizi ve yazılımınızı sürekli gelişen çevrimiçi dünyaya hazırlıyoruz.'],
            ['no' => '04', 'title' => 'Optimizasyon & Dijital Pazarlama', 'desc' => 'SEO, Google Ads ve pazaryeri entegrasyonlarıyla markanızı düşük maliyetle 7/24 pazarlama fırsatına kavuşturuyoruz.'],
            ['no' => '05', 'title' => 'Mükemmel Destek & Süreklilik', 'desc' => 'Teslim sonrasında da hızlı teknik destek, düzenli yedekleme ve eğitimlerle her aşamada birlikte büyüyoruz.'],
        ],
    ],

    /* ---------------------------------------------------------- Fiyatlar */
    'pricing' => [
        'eyebrow' => 'Web Tasarım & E-Ticaret Paketlerimiz',
        'title' => 'İhtiyacınıza uygun profesyonel paketi seçin',
        'description' => 'Hazır web site paketlerimizden yıllık gelişmiş e-ticaret paketlerimize kadar tüm çözümlerimizde güçlü SEO, SSL ve yönetim paneli standarttır.',
        'note' => 'Özel teklif ve modül talepleri için WhatsApp\'tan hemen bilgi alın.',
        'plans' => [
            [
                'name' => 'Kurumsal Web Paketi (Special)',
                'price' => 'Teklif Alın',
                'period' => 'Anahtar Teslim Kurumsal Site',
                'delivery' => 'Hemen Kullan & Özelleştirilebilir Tasarım',
                'desc' => 'Kurumsal firmalar için güçlü SEO altyapılı, yönetim panelli eksiksiz web tasarım paketi.',
                'popular' => false,
                'features' => [
                    'Güçlü SEO Yapısı & Google Mobil Uyumluluk',
                    'Ücretsiz Hosting & SSL Güvenlik Sertifikası',
                    'Kurumsal Mail Adresi (4 Adet)',
                    'Gelişmiş Türkçe Yönetim Paneli',
                    'Sınırsız Sayfa, Blog, Kategori & Etiket',
                    'Ürün / Hizmet & Referans Modülü',
                    'WhatsApp Canlı Destek & İletişim Formu',
                    'Anahtar Kelime Optimizasyonları',
                ],
            ],
            [
                'name' => 'Standart / Premium E-Ticaret',
                'price' => 'Teklif Alın',
                'period' => 'Yıllık E-Ticaret Paketi',
                'delivery' => 'Pazaryeri & 21 Banka POS Entegreli',
                'desc' => '7/24 online satış yapmak isteyen markalar için pazaryeri ve mobil uygulama destekli e-ticaret paketi.',
                'popular' => true,
                'features' => [
                    'Ücretsiz Alan Adı (.com), Web Alanı, Trafik & SSL',
                    'N11, Hepsiburada, Amazon.com.tr & ePttAVM Entegrasyonu',
                    'InstaShop Modülü & 21 Banka Sanal POS',
                    'iOS & Android Mobil Uygulama Desteği',
                    'Sipariş, Kargo, İptal/İade & Havale/EFT Yönetimi',
                    'Manuel, Excel ve XML ile Toplu Ürün Yükleme/Çıktı',
                    'Sınırsız Yönetici Paneli Eğitimi',
                    'WhatsApp Sipariş & Canlı Destek Hattı',
                ],
            ],
            [
                'name' => 'Paket Unlimited (Tam Kapsam)',
                'price' => 'Teklif Alın',
                'period' => 'Sınırsız Web & Katalog Sistemi',
                'delivery' => 'Çok Dilli & Tam Otomasyon',
                'desc' => 'Sınırsız web tasarım paketi, QR katalog ve çoklu dil desteği ile dijitalde en güçlü siz olun.',
                'popular' => false,
                'features' => [
                    'Special Paketteki Tüm Özellikler Dahil',
                    'Gelişmiş Katalog Sistemi & QR Katalog Modülü',
                    'Çoklu Dil Yönetimi (2 Adet Dil Desteği)',
                    'Instagram & YouTube Dinamik Feed Entegrasyonu',
                    'Arama Motoru Kaydı & Dinamik Site Haritası',
                    'Kırık Link Kontrolü & Etkileşim Paylaşımları',
                    'Otomatik Yedekleme & 24 Saat Kurtarma Garantisi',
                    'Size Özel Ek Modül Geliştirme Desteği',
                ],
            ],
        ],
    ],

    /* ----------------------------------------------------------- Yorumlar */
    'testimonials' => [
        'eyebrow' => 'Müşteri Yorumları',
        'title' => '300’den fazla marka bizimle çalışıyor',
        'description' => 'Hükümdar Bilişim ile dijital dönüşümünü gerçekleştiren markalarımızın deneyimleri.',
        'items' => [
            ['quote' => 'Web sitemizi yeniden tasarladılar ve sonuç harikaydı! Modern, kullanıcı dostu ve tam istediğimiz gibi bir iş ortaya koydular.', 'name' => 'Beklentilerimizin Ötesinde', 'role' => 'Kurumsal Web Tasarım Müşterisi'],
            ['quote' => 'Hükümdar Bilişim, markamızı dijital dünyada doğru şekilde konumlandırmamıza yardımcı oldu. Hızlı ve etkili çözümleriyle beklentilerimizi karşıladılar.', 'name' => 'Profesyonel ve Hızlı Hizmet', 'role' => 'E-Ticaret & Dijital Pazarlama Müşterisi'],
            ['quote' => 'Reklam kampanyalarımızda büyük bir dönüşüm sağladılar. Sayelerinde daha fazla müşteriye ulaşmayı başardık.', 'name' => 'Her Zaman Güvenilir', 'role' => 'Google Ads & SEO Müşterisi'],
            ['quote' => 'Özel yazılım ve yönetim paneli sayesinde tüm stok, pazaryeri ve sipariş süreçlerimizi tek ekrandan hatasız yönetiyoruz. Teknik destek ekibi her an yanımızda.', 'name' => 'Kesintisiz Teknik Destek', 'role' => 'B2B & E-Ticaret Yazılım Müşterisi'],
        ],
    ],

    /* --------------------------------------------------------- Referanslar */
    'references' => [
        'eyebrow' => 'Referanslarımız',
        'title' => 'Tamamladığımız projelerden seçkiler',
        'description' => '2008 yılından bu yana kurumsal web tasarım, e-ticaret, özel yazılım ve dijital eğitim platformu alanlarında hayata geçirdiğimiz projeler.',
        'items' => [
            [
                'name' => 'Çiçekçi Sitesi: İşinizi Dijitalde Büyütmenin En Renkli Yolu',
                'slug' => 'cicekci-sitesi',
                'category' => 'E-Ticaret',
                'tag' => 'Hazır Çiçekçi Sitesi',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/cicekci-sitesi-isinizi-dijitalde-buyutmenin-en-renkli-yolu/',
                'image' => 'images/references/hukumdar-cicekci-sitesi-isinizi-dijitalde-b-uy-utmenin-en-renkli-yolu.png',
            ],
            [
                'name' => 'Burger Web Sitesi',
                'slug' => 'burger-web-sitesi',
                'category' => 'Web Tasarım',
                'tag' => 'Restoran & QR Menü',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/burger-web-sitesi/',
                'image' => 'images/references/hukumdar-burger-web-sitesi.png',
            ],
            [
                'name' => 'Temizlik Firması Web Tasarımı (Pozcu Temizlik)',
                'slug' => 'temizlik-firmasi-web-tasarimi',
                'category' => 'Web Tasarım',
                'tag' => 'Kurumsal Hizmet',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/temizlik-firmasi-web-tasarimi/',
                'image' => 'images/references/hukumdar-temizlik-firmasi-web-tasarimi.jpeg',
            ],
            [
                'name' => 'Medikal Web Tasarım (Adveka Medikal)',
                'slug' => 'medikal-web-tasarim',
                'category' => 'Web Tasarım',
                'tag' => 'Sağlık & Medikal',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/medikal-web-tasarim/',
                'image' => 'images/references/hukumdar-medikal-web-tasarim.jpeg',
            ],
            [
                'name' => 'Yazar Kevser Demet Web Sitesi',
                'slug' => 'yazar-kevser-demet-web-sitesi',
                'category' => 'Web Tasarım',
                'tag' => 'Kişisel & Yazar',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/yazar-kevser-demet-web-sitesi/',
                'image' => 'images/references/hukumdar-yazar-kevser-demet-web-sitesi.png',
            ],
            [
                'name' => 'Citymate — Şehir Dostu Taşıma Deneyimi',
                'slug' => 'citymate',
                'category' => 'E-Ticaret',
                'tag' => 'Elektrikli Mobilite',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/citymate-sehir-dostu-tasima-deneyimi/',
                'image' => 'images/references/hukumdar-citymate-sehir-dostu-tasima-deneyimi.jpg',
            ],
            [
                'name' => 'ERST GROUP — Dış Ticarette Dijital Yüz',
                'slug' => 'erst-group',
                'category' => 'Web Tasarım',
                'tag' => 'Dış Ticaret',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/erst-group-dis-ticarette-dijital-yuz/',
                'image' => 'images/references/hukumdar-erst-group-dis-ticarette-dijital-y-uz.jpg',
            ],
            [
                'name' => 'frhdesign — El İşçiliğinde Dijital Dokunuş',
                'slug' => 'frhdesign',
                'category' => 'E-Ticaret',
                'tag' => 'Ahşap & Tasarım',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/frhdesign-el-isciliginde-dijital-dokunus/',
                'image' => 'images/references/hukumdar-frhdesign-el-isciliginde-dijital-dokunus.jpg',
            ],
            [
                'name' => 'İMGE VIP — Dijital Eğitim Platformu Tasarımı',
                'slug' => 'imge-vip',
                'category' => 'Özel Yazılım',
                'tag' => 'Eğitim Platformu',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/imge-vip-dijital-egitim-platformu-tasarimi/',
                'image' => 'images/references/hukumdar-imge-vip-dijital-egitim-platformu-tasarimi.jpg',
            ],
            [
                'name' => 'Lacivert Mimarlık — Endüstriyel Çözümler İçin Dijital Vitrin',
                'slug' => 'lacivert-mimarlik',
                'category' => 'Web Tasarım',
                'tag' => 'Mimarlık & Üretim',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/lacivert-mimarlik-endustriyel-cozumler-icin-dijital-vitrin/',
                'image' => 'images/references/hukumdar-lacivert-mimarlik-end-ustriyel-c-oz-umler-icin-dijital-vitrin.jpg',
            ],
            [
                'name' => 'Loop Bisiklet — Sürüş Keyfi Dijitale Taşındı',
                'slug' => 'loop-bisiklet',
                'category' => 'E-Ticaret',
                'tag' => 'Spor & Bisiklet',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/loop-bisiklet-surus-keyfi-dijitale-tasindi/',
                'image' => 'images/references/hukumdar-loop-bisiklet-s-ur-us-keyfi-dijitale-tasindi.jpg',
            ],
            [
                'name' => 'LUWISCHE — Bilimle Gelen Güzellik',
                'slug' => 'luwische',
                'category' => 'E-Ticaret',
                'tag' => 'Dermokozmetik',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/luwische-bilimle-gelen-guzellik/',
                'image' => 'images/references/hukumdar-luwische-bilimle-gelen-g-uzellik.jpg',
            ],
            [
                'name' => 'Past & Future — Estetik Kliniklere Açılan Dijital Kapı',
                'slug' => 'past-future',
                'category' => 'Web Tasarım',
                'tag' => 'Sağlık Turizmi',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/past-future-estetik-kliniklere-acilan-dijital-kapi/',
                'image' => 'images/references/hukumdar-past-future-estetik-kliniklere-acilan-dijital-kapi.jpg',
            ],
            [
                'name' => 'Vodafone Bayi Giriş Sistemi Arayüzü',
                'slug' => 'vodafone-bayi-giris-sistemi',
                'category' => 'Özel Yazılım',
                'tag' => 'B2B Bayi Portalı',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/vodafone-bayi-giris-sistemi-arayuzu/',
                'image' => 'images/references/hukumdar-vodafone-bayi-giris-sistemi-aray-uz-u.jpg',
            ],
            [
                'name' => 'AIRLED — Aydınlatmanın Yeni Dili',
                'slug' => 'airled',
                'category' => 'Web Tasarım',
                'tag' => 'LED Aydınlatma',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/airled-aydinlatmanin-yeni-dili/',
                'image' => 'images/references/hukumdar-airled-aydinlatmanin-yeni-dili.jpg',
            ],
            [
                'name' => 'BAM — Birleşik Arabuluculuk Merkezleri',
                'slug' => 'bam-arabuluculuk',
                'category' => 'Web Tasarım',
                'tag' => 'Hukuk & Danışmanlık',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/bam-birlesik-arabuluculuk-merkezleri-kurumsal-web-sitesi/',
                'image' => 'images/references/hukumdar-bam-birlesik-arabuluculuk-merkezleri-kurumsal-web-sitesi.jpg',
            ],
            [
                'name' => 'Bestech Bilişim — %100 Güvenli Teknik Destek',
                'slug' => 'bestech-bilisim',
                'category' => 'Web Tasarım',
                'tag' => 'Bilişim & Teknik Servis',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/bestech-bilisim-%100-guvenli-teknik-destek/',
                'image' => 'images/references/hukumdar-bestech-bilisim-100-g-uvenli-teknik-destek.jpg',
            ],
            [
                'name' => 'Batuhan Yachting — Maviliklerle Buluşan Dijital Deneyim',
                'slug' => 'batuhan-yachting',
                'category' => 'Web Tasarım',
                'tag' => 'Yatçılık & Turizm',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/batuhan-yatching-maviliklerle-bulusan-dijital-deneyim/',
                'image' => 'images/references/hukumdar-batuhan-yatching-maviliklerle-bulusan-dijital-deneyim.jpg',
            ],
            [
                'name' => 'Birsor — Küresel Düşünen Danışmanlık Hizmeti',
                'slug' => 'birsor-danismanlik',
                'category' => 'Web Tasarım',
                'tag' => 'Küresel Danışmanlık',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/birsor-kuresel-dusunen-danismanlik-hizmeti/',
                'image' => 'images/references/hukumdar-birsor-k-uresel-d-us-unen-danismanlik-hizmeti.jpg',
            ],
            [
                'name' => 'Antalya VIP Transferi — Konforlu Yolculukların Dijital Yüzü',
                'slug' => 'antalya-vip-transfer',
                'category' => 'Özel Yazılım',
                'tag' => 'VIP Transfer & Rezervasyon',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/antalya-vip-transferi-konforlu-yolculuklarin-dijital-yuzu/',
                'image' => 'images/references/hukumdar-antalya-vip-transferi-konforlu-yolculuklarin-dijital-y-uz-u.jpg',
            ],
            [
                'name' => 'Asay Yemek — Lezzetin Dijital Sunumu',
                'slug' => 'asay-yemek',
                'category' => 'Web Tasarım',
                'tag' => 'Catering & Gıda',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/asay-yemek-lezzetin-dijital-sunumu/',
                'image' => 'images/references/hukumdar-asay-yemek-lezzetin-dijital-sunumu.jpg',
            ],
            [
                'name' => 'Loca Hill — Doğayla İç İçe Bir Dijital Deneyim',
                'slug' => 'loca-hill',
                'category' => 'Web Tasarım',
                'tag' => 'Konaklama & Yaşam',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/loca-hill-dogayla-ic-ice-bir-dijital-deneyim/',
                'image' => 'images/references/hukumdar-loca-hill-dogayla-ic-ice-bir-dijital-deneyim.png',
            ],
            [
                'name' => 'KN33 Express — Güvenli ve Kesintisiz Taşımacılık Çözümü',
                'slug' => 'kn33-express',
                'category' => 'Web Tasarım',
                'tag' => 'Lojistik & Taşımacılık',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/kn33-express-guvenli-ve-kesintisiz-tasimacilik-cozumu/',
                'image' => 'images/references/hukumdar-kn33-express-g-uvenli-ve-kesintisiz-tasimacilik-c-oz-um-u.png',
            ],
            [
                'name' => 'Dualtron — Web Sitesi Tasarımı ve Yayına Alma Süreci',
                'slug' => 'dualtron',
                'category' => 'E-Ticaret',
                'tag' => 'Elektrikli Scooter',
                'url' => 'https://hukumdar.com.tr/referanslarimiz/dualtron-web-sitesi-tasarimi-ve-yayina-alma-sureci/',
                'image' => 'images/references/hukumdar-dualtron-web-sitesi-tasarimi-ve-yayina-alma-s-ureci.png',
            ],
        ],
    ],

    /* --------------------------------------------------------------- SSS */
    'faq' => [
        'eyebrow' => 'Sıkça Sorulan Sorular',
        'title' => 'E-Ticaret, Web Tasarım ve SEO hakkında merak edilenler',
        'description' => 'Hükümdar Bilişim uzman ekibinin en sık yanıtladığı sorular ve stratejik cevapları.',
        'items' => [
            ['q' => 'E‑ticarette başarıya başlamak için ilk adımlar nelerdir?', 'a' => 'Pazar ve rakip analizi yapın, doğru nişi belirleyin, hedef kitlenizi tanımlayın. Ardından ürün konumlandırması, fiyatlama ve kârlılık hesabı yapın. Güçlü görseller, güven unsurları (3D Secure, SSL) ve net iade/kargo politikasıyla yayına çıkın.'],
            ['q' => 'Doğru e‑ticaret altyapısını seçmek neden kritiktir?', 'a' => 'Altyapı; site hızı, mobil uyumluluk, SEO kabiliyeti, ödeme/kargo entegrasyonları ve güvenlik (PCI DSS, 3D Secure) gibi metrikleri belirler. Doğru altyapı dönüşüm oranını, reklam verimliliğini ve ölçeklenebilirliği artırır; sepet terk oranını düşürür.'],
            ['q' => 'Doğru firmayla çalışmanın e‑ticaret ve web başarısına etkisi nedir?', 'a' => 'Deneyimli bir ekip; strateji, altyapı seçimi, entegrasyon, SEO, performans reklamları ve analitik raporlama süreçlerini tek çatı altında yönetir. Hükümdar Bilişim, 2008’den bu yana teknik kurulumdan dönüşüm optimizasyonuna kadar uçtan uca destek sunar.'],
            ['q' => 'E‑ticaret ve kurumsal sitelerde SEO stratejisi nasıl kurgulanmalı?', 'a' => 'Anahtar kelime araştırması, SEO uyumlu kategori ve ürün açıklamaları, şema işaretlemeleri, düzenli blog içerikleri ve yüksek sayfa hızı (Core Web Vitals) ile kullanıcı niyetiyle uyumlu bir sayfa mimarisi kurgulanmalıdır.'],
            ['q' => 'Google Ads reklam bütçesi ve ROAS nasıl yönetilir?', 'a' => 'Kampanyaları ürün kârlılığına göre segmente ediyor, dönüşüm kaynaklarını doğru kuruyor ve çoklu A/B testleriyle arama, alışveriş ve sosyal medya kanallarını birlikte optimize ederek sağlıklı ROAS elde ediyoruz.'],
            ['q' => 'Web sitemde çökme veya teknik sorun olursa destek sağlıyor musunuz?', 'a' => 'Evet. Hükümdar Bilişim olarak internet sitelerinizin herhangi bir çökme ya da bozulma durumunda 24 saat içerisinde eski haline getirme garantisi ve kesintisiz mühendislik desteği sağlıyoruz.'],
        ],
    ],

    /* ------------------------------------------------------------- Blog */
    'blog' => [
        'eyebrow' => 'Son Yazılarımız',
        'title' => 'Teknoloji, Dijital Pazarlama ve SEO Hakkında Yazılarımız',
        'description' => 'Hükümdar Bilişim uzmanlarından SEO, e-ticaret altyapıları, Google Ads politikaları ve dijital büyüme rehberleri.',
        'items' => [
            [
                'slug' => 'mugla-seo-hizmeti-googleda-ust-siralara-cikin',
                'seo_title' => 'Muğla SEO Hizmeti: Google’da Üst Sıralara Çıkın - Hükümdar Bilişim',
                'title' => 'Muğla SEO Hizmeti: Google’da Üst Sıralara Çıkın',
                'category' => 'SEO Hizmeti',
                'date' => '26 Kasım 2025',
                'read' => '5 dk',
                'image' => 'images/blog/mugla-seo-firmasi.png',
                'excerpt' => 'Sadece güzel bir web sitesine sahip olmak yeterli değildir; potansiyel müşterilerin sizi bulabilmesi için güçlü bir SEO stratejisi gereklidir.',
                'body' => [
                    'Sadece güzel bir web sitesine sahip olmak yeterli değildir; potansiyel müşterilerin sizi bulabilmesi için güçlü bir SEO stratejisi gereklidir. Hükümdar Bilişim, Muğla SEO ve arama motoru optimizasyonu hizmetleriyle web sitenizin organik trafiğini artırmayı hedefler.',
                    'Hükümdar Bilişim ile SEO çalışmasının başlıca avantajları arasında detaylı anahtar kelime analizi, rakip ve sektör analizi, SEO uyumlu içerik üretimi, teknik SEO (site hızı, URL yapısı, mobil uyumluluk, site haritaları) ve doğal backlink çalışmaları yer alır.',
                    '16 yıllık süreçte farklı sektörlerden sayısız web tasarım projesi tamamlanmış, yerel ve ulusal markalara SEO danışmanlığı verilmiş ve uzun vadeli iş birlikleri ile kalıcı başarı hikayeleri oluşturulmuştur.',
                    'İnternette rakiplerinizden öne çıkmak, markanızı doğru kitleye ulaştırmak ve uzun vadeli başarı elde etmek istiyorsanız; Hükümdar Bilişim 16 yıllık deneyimi, geniş referans ağı ve sonuç odaklı SEO stratejileriyle işletmenizi dijital dünyada hak ettiği konuma taşımaya hazırdır.',
                ],
            ],
            [
                'slug' => 'e-ticarette-nasil-basarili-olunur',
                'seo_title' => 'E-Ticarette Nasıl Başarılı Olunur? Doğru Firmayla Çalışmanın Önemi',
                'title' => 'E-Ticarette Nasıl Başarılı Olunur?',
                'category' => 'E-Ticaret',
                'date' => '24 Kasım 2025',
                'read' => '7 dk',
                'image' => 'images/blog/e-ticarette-nasil-basarili-olunur.png',
                'excerpt' => 'Dijital çağın getirdiği olanaklar ticaretin kurallarını baştan sona değiştirdi. 7/24 açık bir mağazaya sahip olmanın ve doğru e-ticaret altyapısının sırları.',
                'body' => [
                    'Dijital çağın getirdiği olanaklar, ticaretin kurallarını baştan sona değiştirdi. Günümüzde sadece fiziksel bir mağazaya sahip olmak yeterli değil; 7/24 açık bir dijital mağazaya sahip olmak rekabetçi piyasada var olmanın anahtarıdır.',
                    'E-ticarette başarılı olmak isteyen her girişimcinin atması gereken ilk adım, binanın temelini yani e-ticaret altyapısını sağlam atmaktır. Hükümdar Bilişim’in sunduğu profesyonel e-ticaret altyapıları; yüksek sayfa açılış hızı, kusursuz mobil uyumluluk ve stok/sipariş/kargo süreçlerini tek panelden yönetme avantajı sağlar.',
                    'Sepeti terk etme (cart abandonment) oranlarını düşürmek için sürpriz maliyetlerden kaçınılmalı, üyeliksiz alışveriş imkanı sunulmalı, tek sayfa ödeme sistemleri kullanılmalı ve SSL ile 3D Secure banka güvenlik logoları görünür şekilde konumlandırılmalıdır.',
                    'Ayrıca tedarikçiden gelen kopya metinler yerine ikna edici, fayda odaklı ve SEO uyumlu özgün ürün açıklamaları ile her açıdan çekilmiş yüksek çözünürlüklü ürün görselleri kullanmak dönüşüm oranlarını doğrudan katlamaktadır.',
                ],
            ],
            [
                'slug' => 'google-adwords-hesabi-neden-askiya-alinir-cozumu-ve-ornek-senaryolar',
                'seo_title' => 'Google AdWords Hesabı Neden Askıya Alınır? Çözümü ve Örnek Senaryolar',
                'title' => 'Google AdWords Hesabı Neden Askıya Alınır? Çözümü ve Örnek Senaryolar',
                'category' => 'Google Ads',
                'date' => '20 Kasım 2025',
                'read' => '6 dk',
                'image' => 'images/blog/google-adwords-hesabi-askiya-alindi.jpeg',
                'excerpt' => 'Google Ads hesabınızın askıya alınma nedenleri, gerçek yaşamdan örnek senaryolar ve hesabınızı yeniden aktif hale getirmek için izlemeniz gereken 5 altın kural.',
                'body' => [
                    'Google AdWords (Google Ads) hesabınızın askıya alınması, dijital dünyada reklam verenlerin en çok karşılaştığı sorunlardan biridir. Google’ın algıladığı politika ihlalleri, fatura/ödeme sorunları veya şüpheli hesap güvenliği aktiviteleri sistemin otomatik olarak hesabı askıya almasına yol açabilir.',
                    'Başlıca askıya alınma nedenleri: (1) Yanıltıcı içerik veya kampanya vaatleri, (2) Eksik/hatalı ödeme ve fatura bilgileri, (3) Farklı şehirlerden veya cihazlardan eşzamanlı şüpheli girişler, (4) Tekrarlanan reklam politikası ihlalleri.',
                    'Hesabınız askıya alındıysa önce paneldeki bildirim sebebini analiz edin, web sitenizdeki gizlilik/iade/iletişim sayfalarını ve reklam metinlerini politikalara uygun şekilde düzeltin, ardından yeni hesap açmak yerine mevcut hesabınız üzerinden kanıtlarıyla birlikte gözden geçirme (itiraz) formunu doldurun.',
                    'Askıya alınmamak için 5 altın kural: Google reklam politikalarını yakından takip edin, sitenizin yasal sayfalarını güncel tutun, güvenli ödeme yöntemleri kullanın, aynı site için birden fazla reklam hesabı açmayın ve reklam vaatlerinizde daima şeffaf olun.',
                ],
            ],
            [
                'slug' => 'internetten-taki-satisi-nasil-yapilir-teknik-ve-seo-uyumlu-rehber-2',
                'seo_title' => 'İnternetten Takı Satışı Nasıl Yapılır? Teknik ve SEO Uyumlu Rehber',
                'title' => 'İnternetten Takı Satışı Nasıl Yapılır? Teknik ve SEO Uyumlu Rehber',
                'category' => 'E-Ticaret',
                'date' => '15 Kasım 2025',
                'read' => '6 dk',
                'image' => 'images/blog/internetten-taki-satisi-nasil-yapilir.jpeg',
                'excerpt' => 'Hükümdar Bilişim’in 1200’den fazla web sitesi tecrübesi ışığında; online takı mağazası kurma, kategori mimarisi, stok yönetimi ve SEO rehberi.',
                'body' => [
                    'İnternetten takı satışı yapmak hem girişimciler hem de geleneksel kuyumcu ve takı markaları için büyük fırsatlar sunuyor. Hükümdar Bilişim’in 2009’dan bu yana 1200’den fazla web sitesi tasarlayarak edindiği tecrübeler, doğru kategori ve teknik altyapının satışları doğrudan belirlediğini gösteriyor.',
                    'Takı koleksiyonunuzu oluştururken kolye, bilezik, küpe, yüzük gibi ana kategorileri; altın, gümüş, pırlanta, doğal taş veya el yapımı gibi alt kategorilerle desteklemek hem kullanıcı deneyimini iyileştirir hem de "el yapımı gümüş yüzük" gibi spesifik Google aramalarında üst sıralara çıkmanızı sağlar.',
                    'Kendi e-ticaret sitenizi kurduğunuzda marka kimliğinizi öne çıkarabilir, pazaryeri komisyonlarına bağlı kalmadan müşteri verilerinizi analiz ederek kişiselleştirilmiş kampanyalar yürütebilirsiniz.',
                    'Başarılı bir online takı mağazasında SSL sertifikası, mobil uyumlu (responsive) tasarım, yüksek açılış hızı, 2 tıklamayla ürüne ulaşan gelişmiş filtreleme ve entegre stok/ödeme yönetimi mutlaka yer almalıdır.',
                ],
            ],
            [
                'slug' => 'yurtdisina-kargo-gondermenin-en-ucuz-yolu-nedir',
                'seo_title' => 'Yurtdışına Kargo Göndermenin En Ucuz Yolu Nedir? E-İhracat Rehberi',
                'title' => 'Yurtdışına Kargo Göndermenin En Ucuz Yolu Nedir?',
                'category' => 'E-İhracat',
                'date' => '10 Kasım 2025',
                'read' => '5 dk',
                'image' => 'images/blog/yurtdisina-kargo.jpg',
                'excerpt' => 'E-ihracat yapan işletmeler ve bireysel göndericiler için yurtdışı kargo maliyetlerini düşürme, desi hesaplama ve entegrasyon ipuçları.',
                'body' => [
                    'E-ihracat ile ürünlerini dünyaya açan işletmeler için lojistik ve yurtdışı kargo maliyetleri rekabet gücünü belirleyen en kritik kalemlerden biridir.',
                    'Paket boyutlarını küçülterek hacimsel ağırlığı (desi) optimize etmek, kargo toplayıcı (entegratör) platformlarla kurumsal anlaşmalar yapmak ve e-ticaret sitenize otomatik kargo takip modülü entegre etmek hem maliyetleri düşürür hem de müşteri memnuniyetini artırır.',
                    'Hükümdar Bilişim e-ticaret ve e-ihracat altyapıları, çoklu dil ve döviz desteğinin yanı sıra uluslararası kargo ve ödeme entegrasyonlarıyla markanızı global pazarlara hazırlar.',
                ],
            ],
            [
                'slug' => 'whatsapp-isletme-hesabi-nedir-nasil-acilir',
                'seo_title' => 'WhatsApp İşletme Hesabı Nedir? Nasıl Açılır? (Adım Adım Rehber)',
                'title' => 'WhatsApp İşletme Hesabı Nedir? Nasıl Açılır? (Adım Adım Rehber)',
                'category' => 'Dijital Pazarlama',
                'date' => '05 Kasım 2025',
                'read' => '4 dk',
                'image' => 'images/blog/whatsapp-isletme-hesabi.jpg',
                'excerpt' => 'Dijital çağda müşterilerle doğrudan ve hızlı iletişim kurmak, katalog paylaşmak ve web sitenizden anlık sipariş almak için WhatsApp Business rehberi.',
                'body' => [
                    'Dijital çağda müşteriyle doğrudan ve hızlı iletişim kurmak, markaların büyümesi için vazgeçilmez bir unsur haline geldi. WhatsApp Business (İşletme Hesabı), işletmelere kurumsal profil, ürün kataloğu, otomatik karşılama mesajları ve hızlı yanıtlar sunar.',
                    'Web sitenize ve e-ticaret mağazanıza entegre edilen WhatsApp canlı destek ve sipariş modülü sayesinde ziyaretçileriniz tek tıkla satış temsilcinize ulaşabilir ve sepet terk oranlarınız minimuma iner.',
                ],
            ],
            [
                'slug' => 'patent-nedir-nasil-alinir-ucreti-ne-kadar',
                'seo_title' => 'Patent Nedir? Nasıl Alınır? Ücreti Ne Kadar? (2025 Rehberi)',
                'title' => 'Patent Nedir? Nasıl Alınır? Ücreti Ne Kadar? (2025)',
                'category' => 'Kurumsal',
                'date' => '01 Kasım 2025',
                'read' => '5 dk',
                'image' => 'images/blog/patent-nedir-nasil-alinir.jpg',
                'excerpt' => 'Markanızı, yazılımınızı ve buluşlarınızı yasal koruma altına almanın yolları: Patent ve marka tescil süreçleri hakkında bilmeniz gerekenler.',
                'body' => [
                    'Patent, bir buluşun veya yenilikçi ürünün başkasının izni olmadan üretilmesini, kullanılmasını veya satılmasını belirli bir süre boyunca engelleyen yasal mülkiyet hakkıdır.',
                    'Dijital dünyada yatırım yaparken alan adınızı (.com / .com.tr), kurumsal kimliğinizi ve marka tescilinizi güvence altına almak, işletmenizin gelecekteki marka değerini korumanın ilk adımıdır.',
                ],
            ],
            [
                'slug' => 'mutlaka-bilmeniz-gereken-e-ticaret-terimleri-rehberi',
                'seo_title' => 'Mutlaka Bilmeniz Gereken E-Ticaret Terimleri – 2025 Rehberi',
                'title' => 'Mutlaka Bilmeniz Gereken E-Ticaret Terimleri – 2025 Rehberi',
                'category' => 'E-Ticaret',
                'date' => '28 Ekim 2025',
                'read' => '6 dk',
                'image' => 'images/blog/e-ticaret-terimleri-rehberi.jpg',
                'excerpt' => 'B2B, B2C, ROAS, ROI, Conversion Rate, 3D Secure, XML Entegrasyonu ve SEO gibi e-ticaret dünyasının temel kavramları.',
                'body' => [
                    'E-ticaret, internet üzerinden ürün ya da hizmet satışı ve satın alım sürecinin dijital ortamda yönetilmesidir. Bu ekosistemi doğru yönetmek için temel performans ve yazılım terimlerine hakim olmak gerekir.',
                    'B2B (şirketler arası ticaret), B2C (şirketten tüketiciye satış), ROAS (reklam harcaması getirisi), XML ürün entegrasyonu, 3D Secure güvenli ödeme ve dönüşüm optimizasyonu (CRO); Hükümdar Bilişim e-ticaret panellerinde günlük olarak yönettiğiniz temel başarı metrikleridir.',
                ],
            ],
        ],
    ],

    /* --------------------------------------------------------------- CTA */
    'cta_band' => [
        'title' => 'İşinizi büyütmeye hazır mısınız?',
        'subtitle' => 'Sonuç odaklı bir dijital pazarlama ve yazılım ajansıyla çalışmak için bizimle iletişime geçin.',
        'description' => 'Dilediğiniz zaman WhatsApp (+90 532 696 21 20) üzerinden bizlerle iletişime geçerek satış öncesi destek ve detaylı bilgi alabilirsiniz.',
    ],

];
